const USER_TICKET_STATUS = {
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  SUCCESS: 'SUCCESS',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED',
};

const USER_TICKET_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
};

module.exports = {
  USER_TICKET_STATUS,
  USER_TICKET_STATUS_VALUES: Object.values(USER_TICKET_STATUS),
  USER_TICKET_VERIFICATION_STATUS,
  USER_TICKET_VERIFICATION_STATUS_VALUES: Object.values(USER_TICKET_VERIFICATION_STATUS),
};
